# Generated by Django 4.1.2 on 2024-02-28 08:41

from django.db import migrations, models
import user.manager


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userauth",
            managers=[
                ("objects", user.manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="userauth",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Is Admin"),
        ),
        migrations.AddField(
            model_name="userauth",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
    ]
