# Generated by Django 4.2.10 on 2024-05-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("user", "0003_clientuser_masteruser_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_client",
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name="clientuser",
            table=None,
        ),
        migrations.AlterModelTable(
            name="masteruser",
            table=None,
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
