# Generated by Django 4.2.10 on 2024-05-12 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only 7 - 15 digits are allowed.",
                        regex="^\\+?1?\\d{7,15}$",
                    )
                ],
                verbose_name="Phone No.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
