# Generated by Django 4.1.2 on 2024-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basevehicle",
            name="removed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Removed At"),
        ),
    ]
