# Generated by Django 4.1.2 on 2024-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclerent",
            name="is_rent",
            field=models.BooleanField(default=False, verbose_name="Is Rent"),
        ),
    ]
