---
name: Testing

on: [pull_request]

jobs:
  linting:
    name: Check Linting
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: | 
          echo "${{ secrets.ENV_FILE }}" > backend/.env
          docker-compose run --rm backend sh -c "flake8"
  testing:
    name: Check Unit Testing
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing
        run: | 
          echo "${{ secrets.ENV_FILE }}" > backend/.env
          docker-compose run --rm backend sh -c "python manage.py test"