# Generated by Django 4.1.2 on 2024-02-28 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="Title"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        default="anonymous",
                        max_length=100,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        max_length=200, null=True, verbose_name="Customer Email"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only 7 - 15 digits are allowed.",
                                regex="^\\+?1?\\d{7,15}$",
                            )
                        ],
                        verbose_name="Phone No.",
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "is_solved",
                    models.BooleanField(default=False, verbose_name="Is Solved"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified At"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
