# Generated by Django 4.1.2 on 2024-02-28 02:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="created",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_detail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_status",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_title",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="user_email",
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer_email",
            field=models.EmailField(
                max_length=200, null=True, verbose_name="Customer Email"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer_name",
            field=models.CharField(
                default="anonymous", max_length=100, verbose_name="Customer Name"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="customer_phone",
            field=models.CharField(
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only 7 - 15 digits are allowed.",
                        regex="^\\+?1?\\d{7,15}$",
                    )
                ],
                verbose_name="Phone No.",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_solved",
            field=models.BooleanField(default=False, verbose_name="Is Solved"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified At"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="title",
            field=models.CharField(max_length=50, null=True, verbose_name="Title"),
        ),
    ]
